# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fP4nXg1NnkeM5cgKfIV_DLOOCcJsnPdo
"""

import pandas as pd
import requests

response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

temp_df.head()

df = pd.DataFrame()

df

for i in range(1,500):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=7099c1b6287036ba4094d1b8813eaec3&language=en-US&page={}'.format(i))
    temp2_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp2_df,ignore_index=True)

df